server:
  port: 8081

spring:
  application:
    name: Prometheus Lesson Application
    version: v0.1.0-beta.1

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    enabled: true
    doc-expansion: none
  writer-with-order-by-keys: true
